# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: shuqi 书旗小说&极速版

on:
  workflow_dispatch:
  schedule:
    - cron: '17 0-23 * * *'
  watch:
    types: started
  repository_dispatch:
    types: shuqi
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: 
          git clone https://github.com/2440194388/Wool-script.git ~/scripts
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          cd ~/scripts
          npm install
      - name: '运行 【书旗小说&极速版】'
        run: |
          cd ~/scripts
          node shuqi.js
        env:
          #标准版
          SQ_shuqiuserURL: ${{ secrets.SQ_SHUQIUSERURL }}
          SQ_shuqisyURL: ${{ secrets.SQ_SHUQISYURL }}
          SQ_shuqisyBODY: ${{ secrets.SQ_SHUQISYBODY }}
          SQ_shuqispBODY: ${{ secrets.SQ_SHUQISPBODY }}
          SQ_shuqiscBODY: ${{ secrets.SQ_SHUQISCBODY }}
          SQ_shuqiydBODY: ${{ secrets.SQ_SHUQIYDBODY }}
          SQ_shuqiqdBODY: ${{ secrets.SQ_SHUQIQDBODY }}
          SQ_shuqirwBODY: ${{ secrets.SQ_shuqiRWBODY }}
          SQ_shuqifxBODY: ${{ secrets.SQ_SHUQIFXBODY }}
          SQ_shuqisprwURL: ${{ secrets.SQ_SHUQISPRWURL }}
          SQ_shuqijlBODY: ${{ secrets.SQ_SHUQIJLBODY }}
          SQ_shuqisqjlBODY: ${{ secrets.SQ_SHUQISQJLBODY }}
          SQ_shuqicjyURL: ${{ secrets.SQ_SHUQICJYURL }}
          SQ_shuqicjcsBODY: ${{ secrets.SQ_SHUQICJCSBODY }}
          SQ_shuqicjBODY: ${{ secrets.SQ_SHUQICJBODY }}
          SQ_shuqijsspBODY: ${{ secrets.SQ_SHUQIJSSPBODY }}
          SQ_shuqijsydURL: ${{ secrets.SQ_SHUQIJSYDURL }}
          SQ_shuqijsydBODY: ${{ secrets.SQ_SHUQIJSYDBODY }}
          SQ_shuqijsqdBODY: ${{ secrets.SQ_SHUQIJSQDBODY }}
          SQ_shuqijsqdspyURL: ${{ secrets.SQ_SHUQIJSQDSPYURL }}
          SQ_shuqijsqdspBODY: ${{ secrets.SQ_SHUQIJSQDSPBODY }}
          SQ_shuqijsrwBODY: ${{ secrets.SQ_SHUQIJSRWBODY }}
          SQ_shuqijsfxBODY: ${{ secrets.SQ_SHUQIJSFXBODY }}
          SQ_shuqijsbookURL: ${{ secrets.SQ_SHUQIJSBOOKURL }}
          SQ_shuqijsbookBODY: ${{ secrets.SQ_SHUQIJSBOOKBODY }}
          SQ_shuqijssprwURL: ${{ secrets.SQ_SHUQIJSSPRWURL }}
          
          #微信酱
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          #BARK推送
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          #tg推送
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          #钉钉推送
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          #企业微信推送
          QYWX_KEY: ${{ secrets.QYWX_KEY }}
          #iGot推送
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
          #酷推(Cool Push)推送
          QQ_SKEY: ${{ secrets.QQ_SKEY }}
          QQ_MODE: ${{ secrets.QQ_MODE }}
                    #pushplus推送
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
          PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER }}
          #万能推
             
          ALLIN_KEY: ${{ secrets.ALLIN_KEY }} 
          NOTICE_ID: ${{ secrets.NOTICE_ID }}
